'use strict';
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

function sha256File(filePath){return new Promise((resolve,reject)=>{const h=crypto.createHash('sha256');const s=fs.createReadStream(filePath);s.on('data',d=>h.update(d));s.on('end',()=>resolve(h.digest('hex')));s.on('error',reject);});}
function tokenHash(token){return crypto.createHash('sha256').update(String(token)).digest('hex');}
function bearer(req){const h=String(req.headers.authorization||'');return h.startsWith('Bearer ')?h.slice(7).trim():'';}

function register({app,q,auth,adminOnly,notifyPlayer,MEDIA_ROOT,PUBLIC_BASE_URL}){
  async function findScreenByCode(code){return (await q('SELECT * FROM cx_screens WHERE pairing_code=$1',[String(code||'').trim().toUpperCase()])).rows[0]||null;}
  async function authenticatePlayer(req,res){const screen=await findScreenByCode(req.params.code);if(!screen){res.status(404).json({error:'Code écran introuvable'});return null;}const token=bearer(req);if(screen.player_token_hash&&tokenHash(token)!==screen.player_token_hash){res.status(401).json({error:'Jeton player invalide'});return null;}return screen;}
  async function createCommand(screenId,type,payload,requestedBy,sourceType,sourceId){const r=await q(`INSERT INTO cx_player_commands(screen_id,type,payload,status,requested_by,source_type,source_id)
    VALUES($1,$2,$3::jsonb,'PENDING',$4,$5,$6) RETURNING *`,[screenId,type,JSON.stringify(payload||{}),requestedBy||null,sourceType||null,sourceId||null]);return r.rows[0];}
  async function queueForScreen(screen,type,payload,userId,sourceType,sourceId){const cmd=await createCommand(screen.id,type,payload,userId,sourceType,sourceId);const realtime=notifyPlayer(screen.pairing_code,{type:'command',commandId:cmd.id,command:cmd.type});return {...cmd,realtime};}
  async function screenConfig(screen,req){
    const playlistIds=[screen.playlist_a_id,screen.playlist_b_id].filter(Boolean);
    const playlists={};
    for(const id of [...new Set(playlistIds)]){
      const p=(await q('SELECT * FROM cx_playlists WHERE id=$1',[id])).rows[0];
      if(!p)continue;
      const items=(await q(`SELECT i.*,m.title media_title,m.file_name,m.original_name,m.mime_type,m.media_type,m.bytes,m.updated_at media_updated_at
        FROM cx_playlist_items i LEFT JOIN cx_media m ON m.id=i.media_id WHERE i.playlist_id=$1 AND i.active=true ORDER BY i.position,i.id`,[id])).rows;
      playlists[id]={...p,items:items.map(it=>({...it,media_url:it.file_name?`${PUBLIC_BASE_URL||req.protocol+'://'+req.get('host')}/files/uploads/${encodeURIComponent(it.file_name)}`:null}))};
    }
    const rules=(await q('SELECT * FROM cx_screen_schedule_rules WHERE screen_id=$1 AND active=true ORDER BY zone,priority DESC,id',[screen.id])).rows;
    return {protocol:'cx-player-v1',screen:{id:screen.id,name:screen.name,pairing_code:screen.pairing_code,width_px:screen.width_px,height_px:screen.height_px,orientation:screen.orientation,layout:screen.layout,monitor_id:screen.monitor_id||0,window_x:screen.window_x||0,window_y:screen.window_y||0,standby_color:screen.standby_color,zone_split_percent:screen.zone_split_percent||50,zone_a_name:screen.zone_a_name||'Zone A',zone_b_name:screen.zone_b_name||'Zone B',zone_a_crop_top:screen.zone_a_crop_top||0,zone_a_crop_right:screen.zone_a_crop_right||0,zone_a_crop_bottom:screen.zone_a_crop_bottom||0,zone_a_crop_left:screen.zone_a_crop_left||0,zone_a_crop_mode:screen.zone_a_crop_mode||'HIDE',zone_b_crop_top:screen.zone_b_crop_top||0,zone_b_crop_right:screen.zone_b_crop_right||0,zone_b_crop_bottom:screen.zone_b_crop_bottom||0,zone_b_crop_left:screen.zone_b_crop_left||0,zone_b_crop_mode:screen.zone_b_crop_mode||'HIDE',playlist_a_id:screen.playlist_a_id,playlist_b_id:screen.playlist_b_id,sync_version:Number(screen.sync_version||0),config_version:Number(screen.config_version||1)},playlists,rules,generated_at:new Date().toISOString()};
  }

  app.post('/api/player/pair',async(req,res)=>{try{const code=String(req.body.code||'').trim().toUpperCase();const screen=await findScreenByCode(code);if(!screen)return res.status(404).json({error:'Code écran introuvable'});const token=crypto.randomBytes(32).toString('hex');await q(`UPDATE cx_screens SET player_token_hash=$1,player_id=COALESCE(player_id,$2),paired_at=NOW(),last_seen_at=NOW() WHERE id=$3`,[tokenHash(token),crypto.randomUUID(),screen.id]);res.json({ok:true,token,screen_id:screen.id,screen_name:screen.name,protocol:'cx-player-v1'});}catch(e){res.status(500).json({error:e.message});}});
  app.get('/api/player/:code/config',async(req,res)=>{try{const s=await authenticatePlayer(req,res);if(!s)return;res.json(await screenConfig(s,req));}catch(e){res.status(500).json({error:e.message});}});
  app.get('/api/player/:code/manifest',async(req,res)=>{try{const s=await authenticatePlayer(req,res);if(!s)return;const cfg=await screenConfig(s,req);const files=[];for(const p of Object.values(cfg.playlists)){for(const it of p.items||[]){if(!it.file_name)continue;const fp=path.join(MEDIA_ROOT,'uploads',path.basename(it.file_name));if(!fs.existsSync(fp))continue;files.push({media_id:it.media_id,file_name:it.file_name,size:Number(it.bytes||fs.statSync(fp).size),sha256:await sha256File(fp),url:it.media_url,mime_type:it.mime_type,media_type:it.media_type});}}const dedup=[...new Map(files.map(f=>[f.media_id,f])).values()];res.json({protocol:'cx-player-v1',sync_version:Number(s.sync_version||0),files:dedup});}catch(e){res.status(500).json({error:e.message});}});
  app.get('/api/player/:code/commands',async(req,res)=>{try{const s=await authenticatePlayer(req,res);if(!s)return;const rows=(await q(`UPDATE cx_player_commands SET status='RECEIVED',received_at=COALESCE(received_at,NOW()) WHERE id IN
      (SELECT id FROM cx_player_commands WHERE screen_id=$1 AND status='PENDING' ORDER BY created_at LIMIT 20) RETURNING *`,[s.id])).rows;await q('UPDATE cx_screens SET last_seen_at=NOW() WHERE id=$1',[s.id]);res.json(rows);}catch(e){res.status(500).json({error:e.message});}});
  app.post('/api/player/:code/commands/:id/status',async(req,res)=>{try{const s=await authenticatePlayer(req,res);if(!s)return;const status=String(req.body.status||'').toUpperCase();if(!['RECEIVED','RUNNING','COMPLETED','FAILED'].includes(status))return res.status(400).json({error:'État invalide'});const r=await q(`UPDATE cx_player_commands SET status=$1,result=$2::jsonb,error_message=$3,
      started_at=CASE WHEN $1='RUNNING' THEN COALESCE(started_at,NOW()) ELSE started_at END,
      completed_at=CASE WHEN $1 IN ('COMPLETED','FAILED') THEN NOW() ELSE completed_at END
      WHERE id=$4 AND screen_id=$5 RETURNING *`,[status,JSON.stringify(req.body.result||{}),req.body.error||null,req.params.id,s.id]);if(!r.rows[0])return res.status(404).json({error:'Commande introuvable'});res.json({ok:true,command:r.rows[0]});}catch(e){res.status(500).json({error:e.message});}});

  app.post('/api/v27/screens/:id/sync',adminOnly,async(req,res)=>{try{const mode=String(req.body.mode||'SYNC').toUpperCase();const type=mode==='FORCE'?'SYNC_FORCE':mode==='RESET_CACHE'?'CACHE_RESET_SYNC':'SYNC';const s=(await q(`UPDATE cx_screens SET sync_version=COALESCE(sync_version,0)+1,config_version=COALESCE(config_version,1)+1 WHERE id=$1 RETURNING *`,[req.params.id])).rows[0];if(!s)return res.status(404).json({error:'Écran introuvable'});const cmd=await queueForScreen(s,type,{sync_version:s.sync_version},req.session.userId,'SCREEN',s.id);res.json({ok:true,command:cmd,sync_version:s.sync_version});}catch(e){res.status(500).json({error:e.message});}});
  app.post('/api/v27/playlists/:id/sync',adminOnly,async(req,res)=>{try{const screens=(await q(`UPDATE cx_screens SET sync_version=COALESCE(sync_version,0)+1,config_version=COALESCE(config_version,1)+1 WHERE playlist_a_id=$1 OR playlist_b_id=$1 RETURNING *`,[req.params.id])).rows;const commands=[];for(const s of screens)commands.push(await queueForScreen(s,'SYNC',{playlist_id:Number(req.params.id),sync_version:s.sync_version},req.session.userId,'PLAYLIST',Number(req.params.id)));res.json({ok:true,screens:screens.map(s=>({id:s.id,name:s.name,pairing_code:s.pairing_code})),commands});}catch(e){res.status(500).json({error:e.message});}});
  app.get('/api/v27/screens/:id/commands',auth,async(req,res)=>{try{res.json((await q('SELECT * FROM cx_player_commands WHERE screen_id=$1 ORDER BY created_at DESC LIMIT 100',[req.params.id])).rows);}catch(e){res.status(500).json({error:e.message});}});
  app.post('/api/v27/screens/:id/command',adminOnly,async(req,res)=>{try{const allowed=['SYNC','SYNC_FORCE','CACHE_RESET_SYNC','CAPTURE','ECO_ON','ECO_OFF','RELOAD_PLAYBACK','RESTART_PLAYER','RESTART_WINDOWS','CHECK_UPDATE'];const type=String(req.body.type||'').toUpperCase();if(!allowed.includes(type))return res.status(400).json({error:'Commande non autorisée'});const s=(await q('SELECT * FROM cx_screens WHERE id=$1',[req.params.id])).rows[0];if(!s)return res.status(404).json({error:'Écran introuvable'});res.json({ok:true,command:await queueForScreen(s,type,req.body.payload||{},req.session.userId,'SCREEN',s.id)});}catch(e){res.status(500).json({error:e.message});}});
}
module.exports={register};
