
require('dotenv').config(); const {Pool}=require('pg'); const p=new Pool({connectionString:process.env.DATABASE_URL});
(async()=>{await p.query('BEGIN');try{
 await p.query(`CREATE TABLE IF NOT EXISTS cx_screen_groups(id SERIAL PRIMARY KEY,name VARCHAR(160) NOT NULL,client_id INTEGER REFERENCES cx_clients(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(name,client_id));
 CREATE TABLE IF NOT EXISTS cx_screen_schedule_rules(id SERIAL PRIMARY KEY,screen_id INTEGER NOT NULL REFERENCES cx_screens(id) ON DELETE CASCADE,zone CHAR(1) NOT NULL DEFAULT 'A',playlist_id INTEGER NOT NULL REFERENCES cx_playlists(id) ON DELETE CASCADE,name VARCHAR(180),priority INTEGER NOT NULL DEFAULT 100,active BOOLEAN NOT NULL DEFAULT TRUE,start_date DATE,end_date DATE,days VARCHAR(64) NOT NULL DEFAULT 'all',time_from TIME,time_to TIME,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS cx_slide_templates(id SERIAL PRIMARY KEY,name VARCHAR(180) NOT NULL,client_id INTEGER REFERENCES cx_clients(id) ON DELETE SET NULL,canvas JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS cx_qr_sessions(token TEXT PRIMARY KEY,screen_id INTEGER NOT NULL REFERENCES cx_screens(id) ON DELETE CASCADE,playlist_id INTEGER REFERENCES cx_playlists(id) ON DELETE SET NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS cx_screen_captures(id SERIAL PRIMARY KEY,screen_id INTEGER NOT NULL REFERENCES cx_screens(id) ON DELETE CASCADE,image_data TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS cx_api_triggers(id SERIAL PRIMARY KEY,token TEXT NOT NULL UNIQUE DEFAULT md5(random()::text||clock_timestamp()::text),screen_id INTEGER NOT NULL REFERENCES cx_screens(id) ON DELETE CASCADE,label VARCHAR(180) NOT NULL,widget_config JSONB NOT NULL DEFAULT '{}'::jsonb,duration_seconds INTEGER NOT NULL DEFAULT 30,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 ALTER TABLE cx_folders ADD COLUMN IF NOT EXISTS path TEXT;
 ALTER TABLE cx_screens ADD COLUMN IF NOT EXISTS group_id INTEGER REFERENCES cx_screen_groups(id) ON DELETE SET NULL,ADD COLUMN IF NOT EXISTS crop_top INTEGER NOT NULL DEFAULT 0,ADD COLUMN IF NOT EXISTS crop_right INTEGER NOT NULL DEFAULT 0,ADD COLUMN IF NOT EXISTS crop_bottom INTEGER NOT NULL DEFAULT 0,ADD COLUMN IF NOT EXISTS crop_left INTEGER NOT NULL DEFAULT 0;`);
 await p.query('UPDATE cx_folders SET path=COALESCE(path,name) WHERE path IS NULL');await p.query('COMMIT');console.log('Migration V3 terminée.');
}catch(e){await p.query('ROLLBACK');throw e}finally{await p.end()}})().catch(e=>{console.error(e);process.exit(1)});
